config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  mount Sidekiq::Web => '/sidekiq'

  root 'application#index'
  get 'seen' => 'application#images_list'

end

app/models/arr_image.rb
class ArrImage < ActiveRecord::Base

  def url
    "https://s3-eu-west-1.amazonaws.com/arrival-countdown/public/#{name}.jpg"
  end

end

app/models/aws_file.rb
# Amazon web services file handling
class AwsFile
  attr_reader :aws_region, :aws_bucket_name
  attr_accessor :aws_bucket_key

  def initialize(aws_bucket_key)
    @aws_bucket_key = aws_bucket_key
    @aws_bucket_name = DEFAULT_AWS_BUCKET
    @aws_region = DEFAULT_AWS_REGION
    @s3 = Aws::S3::Resource.new(region: DEFAULT_AWS_REGION)
    @remote_file = @s3.bucket(DEFAULT_AWS_BUCKET).object(aws_bucket_key)
  end

  def self.all
    @all_objects ||= Aws::S3::Resource.new(region: DEFAULT_AWS_REGION).bucket(DEFAULT_AWS_BUCKET).objects
  end

  def download_url
    "https://#{AWS_BUCKET_ENDPOINTS.fetch(aws_bucket_name)}/#{aws_bucket_key}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @image = ArrImage.order(:created_at).last
    @image_url = @image.url
  end

  def images_list
    @images = ArrImage.order('created_at DESC')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/images_list.html.erb
<%= link_to root_path do %>
  <h1 class="waiting">Go back</h1>
<% end %>

<% @images.each do |image| %>
  <%= link_to image.url, class: 'seen-image-href' do %>
    <%= image_tag image.url, class: 'seen-image' %>
  <% end %>
<% end %>

app/views/application/index.html.erb
<h1 class="waiting">
  Už jen <%= (DateTime.civil(2016,12,13) - DateTime.now).to_i %> dní! Miluji Tě!
</h1>
<%= image_tag @image_url, class: "absoluteCenter" %>

<%= link_to seen_path, class: 'seen-pictures' do %>
  <h3>Seen pictures</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArrivalCountdown</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="robots" content="noindex, nofollow">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= yield %>

</body>
</html>